# Generated by Django 5.2.8 on 2025-11-20 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Outline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "structure_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full outline structure data in JSON format",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Outline",
                "verbose_name_plural": "Outlines",
                "db_table": "outlines",
            },
        ),
        migrations.CreateModel(
            name="OutlineSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_title",
                    models.CharField(help_text="Title of the section", max_length=500),
                ),
                (
                    "section_type",
                    models.CharField(
                        help_text="Type of section (introduction, literature_review, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "word_count",
                    models.IntegerField(
                        default=0, help_text="Target word count for this section"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of the section in the outline"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outline",
                    models.ForeignKey(
                        help_text="Outline this section belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="projects.outline",
                    ),
                ),
                (
                    "parent_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent section (null for top-level sections)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="projects.outlinesection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outline Section",
                "verbose_name_plural": "Outline Sections",
                "db_table": "outline_sections",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Research topic or thesis title", max_length=500
                    ),
                ),
                (
                    "citation_style",
                    models.CharField(
                        default="APA",
                        help_text="Citation style (APA, MLA, Chicago, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("researching", "Researching"),
                            ("outlined", "Outlined"),
                            ("writing", "Writing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        help_text="Current status of the project",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="outline",
            name="project",
            field=models.OneToOneField(
                help_text="Project this outline belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outline",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "research_summary",
                    models.TextField(
                        help_text="Overall research summary and main themes"
                    ),
                ),
                (
                    "research_gaps",
                    models.TextField(
                        blank=True, help_text="Identified research gaps", null=True
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Recommended research directions",
                        null=True,
                    ),
                ),
                (
                    "total_sources_found",
                    models.IntegerField(
                        default=0, help_text="Total number of sources found"
                    ),
                ),
                (
                    "pdf_sources_count",
                    models.IntegerField(
                        default=0, help_text="Number of PDF sources found"
                    ),
                ),
                (
                    "web_sources_count",
                    models.IntegerField(
                        default=0, help_text="Number of web sources found"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        help_text="Project this research belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research",
                "verbose_name_plural": "Research",
                "db_table": "research",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_title",
                    models.CharField(help_text="Title of the section", max_length=500),
                ),
                (
                    "section_type",
                    models.CharField(help_text="Type of section", max_length=100),
                ),
                ("content", models.TextField(help_text="Full content in MDX format")),
                (
                    "word_count",
                    models.IntegerField(
                        default=0, help_text="Actual word count of the content"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Order of the section"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outline_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the outline section this was based on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="written_sections",
                        to="projects.outlinesection",
                    ),
                ),
                (
                    "parent_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent section (null for top-level sections)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="projects.section",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this section belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "db_table": "sections",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the source", max_length=500),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Paper"),
                            ("book", "Book"),
                            ("article", "Article"),
                            ("website", "Website"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        default="academic",
                        help_text="Type of source",
                        max_length=20,
                    ),
                ),
                (
                    "authors",
                    models.JSONField(
                        blank=True, default=list, help_text="List of authors"
                    ),
                ),
                (
                    "publication_year",
                    models.IntegerField(
                        blank=True, help_text="Year of publication", null=True
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the source",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="DOI identifier",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        blank=True, help_text="Abstract of the source", null=True
                    ),
                ),
                (
                    "key_findings",
                    models.TextField(
                        blank=True,
                        help_text="Key findings extracted from the source",
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of the source",
                        null=True,
                    ),
                ),
                (
                    "full_content",
                    models.TextField(
                        blank=True,
                        help_text="Full content scraped from the source",
                        null=True,
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        blank=True, help_text="Relevance score (0.0 to 1.0)", null=True
                    ),
                ),
                (
                    "relevance_reason",
                    models.TextField(
                        blank=True, help_text="Reason for relevance score", null=True
                    ),
                ),
                (
                    "citation_text",
                    models.TextField(
                        blank=True,
                        help_text="Formatted citation in project citation style",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this source belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
                "db_table": "sources",
                "ordering": ["-relevance_score", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="outlinesection",
            index=models.Index(
                fields=["outline", "order"], name="outline_sec_outline_1702fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outlinesection",
            index=models.Index(
                fields=["parent_section"], name="outline_sec_parent__226662_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "-created_at"], name="projects_user_id_58d805_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="projects_status_6303d7_idx"),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["project", "order"], name="sections_project_e30340_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["parent_section"], name="sections_parent__d36ecb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["section_type"], name="sections_section_595447_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["project", "-relevance_score"],
                name="sources_project_8e4f2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["source_type"], name="sources_source__65c870_idx"
            ),
        ),
    ]
